apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: p-ss9zr-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-admin
  template:
    metadata:
      labels:
        app: hello-admin
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - args:
            - java
            - -jar
            - hello-0.0.1-SNAPSHOT.jar
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          imagePullPolicy: Always
          ports:
            - containerPort: 8585     
              hostPort: 8585
          name: hello-admin
