apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-admin
  template:
    metadata:
      labels:
        app: hello-admin
    spec:
      containers:
        - name: hello 
        - args:
            - java
            - -jar
            - hello-0.0.1-SNAPSHOT.jar
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          imagePullPolicy: Always
